name: CI/CD Pipeline

on: 
  push:
    branches:
      - main

jobs:
  lint-test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python/Node (choose your language)
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
        
      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Or npm install
        
      - name: Lint
        run: flake8 .  # Replace with relevant linter
        
      - name: Run tests
        run: pytest tests/  # Or equivalent

      - name: Build Docker image
        run: docker build -t app:latest .

  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Trivy scan
        run: trivy image app:latest
        
      - name: SonarQube analysis
        run: ./scripts/sonar-scanner.sh  # Script for SonarQube setup

  deploy:
    runs-on: ubuntu-latest
    needs: [lint-test-build, security-scan]
    steps:
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: '1.24.0'
        
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f kubernetes/
